export const PLACE_ORDER_START = "PLACE_ORDER_START";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const CLEAR_ORDER = "CLEAR_ORDER";